services:
  docs:
    image: south_tampa_plants_chatbot_local_docs
    container_name: south_tampa_plants_chatbot_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./south_tampa_plants_chatbot:/app/south_tampa_plants_chatbot:z
    ports:
      - '9000:9000'
    command: /start-docs
