volumes:
  south_tampa_plants_chatbot_local_postgres_data: {}
  south_tampa_plants_chatbot_local_postgres_data_backups: {}
  south_tampa_plants_chatbot_local_redis_data: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: south_tampa_plants_chatbot_local_django
    container_name: south_tampa_plants_chatbot_local_django
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: south_tampa_plants_chatbot_production_postgres
    container_name: south_tampa_plants_chatbot_local_postgres
    expose:
      - "5433" # Publishes 5433 to other containers but NOT to host machine
    ports:
      - "5433:5433"
    volumes:
      - south_tampa_plants_chatbot_local_postgres_data:/south-tampa-plants-data/psql
      - south_tampa_plants_chatbot_local_postgres_data_backups:/south-tampa-plants-data/backups
    env_file:
      - ./.envs/.local/.postgres
    command: -p 5433


  redis:
    image: docker.io/redis:6
    container_name: south_tampa_plants_chatbot_local_redis

    volumes:
      - south_tampa_plants_chatbot_local_redis_data:/data


  celeryworker:
    <<: *django
    image: south_tampa_plants_chatbot_local_celeryworker
    container_name: south_tampa_plants_chatbot_local_celeryworker
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: south_tampa_plants_chatbot_local_celerybeat
    container_name: south_tampa_plants_chatbot_local_celerybeat
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: south_tampa_plants_chatbot_local_flower
    container_name: south_tampa_plants_chatbot_local_flower
    ports:
      - '5555:5555'
    command: /start-flower
